// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebmotorsTeste.Web.Data;

namespace WebmotorsTeste.Web.Migrations
{
    [DbContext(typeof(WebmotorsContext))]
    partial class WebmotorsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("WebmotorsTeste.Web.Models.Anuncio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.Property<string>("Observacao");

                    b.Property<int>("Quilometragem");

                    b.Property<string>("Versao");

                    b.HasKey("Id");

                    b.ToTable("tb_AnuncioWebmotors");
                });
#pragma warning restore 612, 618
        }
    }
}
